"""add_post_type_and_video_url_to_posts

Revision ID: 243b1bddcfc9
Revises: 6eeaf4bc9d17
Create Date: 2026-05-13 00:10:27.371565
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '243b1bddcfc9'
down_revision: Union[str, None] = '6eeaf4bc9d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('video_url', sa.String(length=500), nullable=True))
    op.add_column('posts', sa.Column('post_type', sa.String(length=10), server_default='text', nullable=False))
    op.create_index(op.f('ix_posts_post_type'), 'posts', ['post_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_post_type'), table_name='posts')
    op.drop_column('posts', 'post_type')
    op.drop_column('posts', 'video_url')
    # ### end Alembic commands ###
