"""Add job_posts and job_applications tables

Revision ID: 44451e8e37ed
Revises: a7b8c9d0e1f2
Create Date: 2026-05-15 00:45:18.803028
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44451e8e37ed'
down_revision: Union[str, None] = 'a7b8c9d0e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_posts',
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('job_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_posts_author_id'), 'job_posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_job_posts_created_at'), 'job_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_posts_job_type'), 'job_posts', ['job_type'], unique=False)
    op.create_table('job_applications',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('applicant_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job_posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'applicant_id', name='uq_job_application')
    )
    op.create_index(op.f('ix_job_applications_applicant_id'), 'job_applications', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_job_applications_created_at'), 'job_applications', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_applications_job_id'), 'job_applications', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_applications_job_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_created_at'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_applicant_id'), table_name='job_applications')
    op.drop_table('job_applications')
    op.drop_index(op.f('ix_job_posts_job_type'), table_name='job_posts')
    op.drop_index(op.f('ix_job_posts_created_at'), table_name='job_posts')
    op.drop_index(op.f('ix_job_posts_author_id'), table_name='job_posts')
    op.drop_table('job_posts')
    # ### end Alembic commands ###
