"""add_missing_verification_request_columns

Revision ID: cd78b1bc4ae3
Revises: f6a7b8c9d0e1
Create Date: 2026-06-09 01:13:57.705560
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd78b1bc4ae3'
down_revision: Union[str, None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: unique constraints already exist in DB (created outside Alembic),
    # so we skip them here to avoid DuplicateTableError.
    op.add_column('verification_requests', sa.Column('ocr_extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='OCR-extracted fields: student_name, student_number, university_name, department, expiration_date'))
    op.add_column('verification_requests', sa.Column('ocr_raw_text', sa.Text(), nullable=True, comment='Full raw OCR text output from the document'))
    op.add_column('verification_requests', sa.Column('ai_confidence', sa.Float(), nullable=True, comment='AI confidence score 0.0–1.0. >0.85 auto-approve, <0.4 suspicious'))
    op.add_column('verification_requests', sa.Column('ai_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of AI-detected issues: name_mismatch, blurry, possibly_edited, etc.'))
    op.add_column('verification_requests', sa.Column('ai_validation_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Detailed AI validation breakdown with individual scores'))
    op.add_column('verification_requests', sa.Column('reviewed_by', sa.UUID(), nullable=True))
    op.add_column('verification_requests', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('verification_requests', sa.Column('attempt_number', sa.Integer(), server_default='1', nullable=False, comment='Which attempt this is for this user (1st, 2nd, etc.)'))
    op.add_column('verification_requests', sa.Column('file_size_bytes', sa.Integer(), nullable=True))
    op.add_column('verification_requests', sa.Column('file_content_type', sa.String(length=100), nullable=True))
    op.add_column('verification_requests', sa.Column('file_hash', sa.String(length=128), nullable=True, comment='SHA-256 hash of uploaded file for duplicate detection'))
    op.create_foreign_key('fk_verification_reviewed_by', 'verification_requests', 'users', ['reviewed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_verification_reviewed_by', 'verification_requests', type_='foreignkey')
    op.drop_column('verification_requests', 'file_hash')
    op.drop_column('verification_requests', 'file_content_type')
    op.drop_column('verification_requests', 'file_size_bytes')
    op.drop_column('verification_requests', 'attempt_number')
    op.drop_column('verification_requests', 'reviewed_at')
    op.drop_column('verification_requests', 'reviewed_by')
    op.drop_column('verification_requests', 'ai_validation_details')
    op.drop_column('verification_requests', 'ai_flags')
    op.drop_column('verification_requests', 'ai_confidence')
    op.drop_column('verification_requests', 'ocr_raw_text')
    op.drop_column('verification_requests', 'ocr_extracted_data')
    # ### end Alembic commands ###
